# Generated by Django 5.1.1 on 2024-10-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-time_added',)},
        ),
    ]
