# Generated by Django 5.1.1 on 2024-10-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_like_postlike_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ('-time_added', '-id')},
        ),
    ]
