# Generated by Django 5.1.1 on 2024-11-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_options_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time_added',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Comment like', 'verbose_name_plural': 'Comments likes'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post image', 'verbose_name_plural': 'Posts images'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'Post like', 'verbose_name_plural': 'Posts likes'},
        ),
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ('-time_added', '-id'), 'verbose_name': 'Saved post', 'verbose_name_plural': 'Saved posts'},
        ),
    ]
