# Generated by Django 5.1.1 on 2024-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_exwonderuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exwonderuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='exwonderuser',
            name='penultimate_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предпоследний вход'),
        ),
    ]
