# Generated by Django 5.1.1 on 2024-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_exwonderuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exwonderuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта для аккаунта.', max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
