# Generated by Django 5.1.1 on 2024-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_exwonderuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exwonderuser',
            name='email',
            field=models.EmailField(help_text='Электронная почта для аккаунта.', max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
