# Generated by Django 5.1.1 on 2024-10-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_exwonderuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwonderuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
