# Generated by Django 5.1.1 on 2024-11-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_exwonderuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwonderuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
