# Generated by Django 5.1.1 on 2024-11-22 12:50

import django.contrib.auth.validators
import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_exwonderuser_groups_exwonderuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exwonderuser',
            options={'ordering': ('pk',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='avatar',
            field=models.ImageField(default='default-user-icon.jpg', upload_to=users.models.get_uploaded_avatar_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='Is two factor authentication enabled'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='penultimate_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Penultimate login'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=64, verbose_name='Time zone'),
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='username',
            field=models.CharField(error_messages={'unique': "Username isn't unique."}, max_length=16, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(5)], verbose_name='Username'),
        ),
    ]
