# Generated by Django 5.1.1 on 2024-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0011_alter_exwonderuser_options_alter_exwonderuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exwonderuser',
            index=models.Index(fields=['username'], name='Username index'),
        ),
    ]
