# Generated by Django 5.1.1 on 2024-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_exwonderuser_username_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-pk',), 'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterField(
            model_name='exwonderuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='Is 2FA enabled'),
        ),
    ]
