# Generated by Django 5.1.1 on 2024-11-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwonderuser',
            name='desc',
            field=models.CharField(default='', max_length=1024, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='exwonderuser',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='Name'),
        ),
    ]
