# Generated by Django 5.1.1 on 2024-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_exwonderuser_desc_exwonderuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwonderuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is user online'),
        ),
    ]
