# Generated by Django 5.1.1 on 2025-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_exwonderuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwonderuser',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is account private'),
        ),
    ]
