# Generated by Django 5.1.1 on 2025-02-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_exwonderuser_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwonderuser',
            name='comments_private_status',
            field=models.CharField(choices=[('E', 'Everyone'), ('F', 'Followers'), ('N', 'No one')], default='E', max_length=10),
        ),
    ]
