# Generated by Django 5.1.1 on 2024-12-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import messenger.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_delete", models.BooleanField(default=False)),
                ("members", models.ManyToManyField(related_name="chats", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "db_table": "chats",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=4096, null=True)),
                ("attachment", models.FileField(null=True, upload_to=messenger.models.message_attachments_upload)),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="messenger.chat"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recieved_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sended_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ("-time_added", "-time_updated"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("body__isnull", False), ("attachment__isnull", False), _connector="OR"),
                        name="body_or_attachment_required",
                    )
                ],
            },
        ),
    ]
