# Generated by Django 5.1.1 on 2024-12-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
