# Generated by Django 5.1.1 on 2024-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0002_chat_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_edit",
            field=models.BooleanField(default=False),
        ),
    ]
